# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '/Users/cami/PycharmProjects/projet_onitama/onitama.ui'
#
# Created by: PyQt5 UI code generator 5.15.6
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_OnitamaGameMenu(object):
    def setupUi(self, OnitamaGameMenu):
        OnitamaGameMenu.setObjectName("OnitamaGameMenu")
        OnitamaGameMenu.resize(890, 640)

        self.centralwidget = QtWidgets.QWidget(OnitamaGameMenu)
        self.centralwidget.setObjectName("centralwidget")
        self.container = QtWidgets.QWidget(self.centralwidget)
        self.container.setGeometry(QtCore.QRect(-10, -10, 900, 650))
        self.container.setAutoFillBackground(False)
        self.container.setStyleSheet("")
        self.container.setObjectName("container")
        self.StartGame = QtWidgets.QPushButton(self.container)
        self.StartGame.setGeometry(QtCore.QRect(470, 160, 191, 81))
        #self.StartGame.setCursor(QtGui.QCursor(QtCore.Qt.ArrowCursor))
        self.StartGame.setMouseTracking(True)
        #self.StartGame.setWhatsThis("")
        self.StartGame.setStyleSheet("background-color: rgba(255, 255, 255, 100);")
        self.StartGame.setText("Start Game")
        #self.StartGame.setIconSize(QtCore.QSize(500, 500))
        self.StartGame.setObjectName("StartGame")
        self.quit = QtWidgets.QPushButton(self.container)
        self.quit.setGeometry(QtCore.QRect(500, 300, 111, 41))
        self.quit.setMouseTracking(True)
        self.quit.setStyleSheet("")
        icon = QtGui.QIcon()

        self.quit.setIconSize(QtCore.QSize(500, 500))
        self.quit.setObjectName("quit")
        self.mode_selection = QtWidgets.QGroupBox(self.container)
        self.mode_selection.setGeometry(QtCore.QRect(20, 90, 431, 301))
        font = QtGui.QFont()
        font.setPointSize(13)
        self.mode_selection.setFont(font)
        self.mode_selection.setObjectName("mode_selection")
        self.label = QtWidgets.QLabel(self.mode_selection)
        self.label.setGeometry(QtCore.QRect(20, 30, 91, 51))
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(self.mode_selection)
        self.label_2.setGeometry(QtCore.QRect(160, 30, 101, 51))
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(self.mode_selection)
        self.label_3.setGeometry(QtCore.QRect(300, 30, 111, 51))
        self.label_3.setObjectName("label_3")
        self.mode1 = QtWidgets.QRadioButton(self.mode_selection)
        self.mode1.setGeometry(QtCore.QRect(10, 90, 100, 20))
        self.mode1.setObjectName("mode1")
        self.mode21 = QtWidgets.QRadioButton(self.mode_selection)
        self.mode21.setGeometry(QtCore.QRect(160, 90, 100, 20))
        self.mode21.setObjectName("mode21")
        self.mode22 = QtWidgets.QRadioButton(self.mode_selection)
        self.mode22.setGeometry(QtCore.QRect(160, 120, 111, 20))
        self.mode22.setObjectName("mode22")
        self.mode23 = QtWidgets.QRadioButton(self.mode_selection)
        self.mode23.setGeometry(QtCore.QRect(160, 150, 100, 20))
        self.mode23.setObjectName("mode23")
        self.mode25 = QtWidgets.QRadioButton(self.mode_selection)
        self.mode25.setGeometry(QtCore.QRect(160, 210, 100, 20))
        self.mode25.setObjectName("mode25")
        self.mode24 = QtWidgets.QRadioButton(self.mode_selection)
        self.mode24.setGeometry(QtCore.QRect(160, 180, 100, 20))
        self.mode24.setObjectName("mode24")
        self.mode26 = QtWidgets.QRadioButton(self.mode_selection)
        self.mode26.setGeometry(QtCore.QRect(160, 240, 181, 21))
        self.mode26.setObjectName("mode26")
        self.mode3 = QtWidgets.QRadioButton(self.mode_selection)
        self.mode3.setGeometry(QtCore.QRect(290, 90, 141, 20))
        self.mode3.setObjectName("mode3")
        self.rules = QtWidgets.QPushButton(self.container)
        self.rules.setGeometry(QtCore.QRect(520, 90, 113, 32))
        self.rules.setStyleSheet("")
        self.rules.setObjectName("rules")
        OnitamaGameMenu.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(OnitamaGameMenu)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 800, 24))
        self.menubar.setObjectName("menubar")
        OnitamaGameMenu.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(OnitamaGameMenu)
        self.statusbar.setObjectName("statusbar")
        OnitamaGameMenu.setStatusBar(self.statusbar)

        self.retranslateUi(OnitamaGameMenu)
        self.quit.clicked.connect(OnitamaGameMenu.close) # type: ignore
        QtCore.QMetaObject.connectSlotsByName(OnitamaGameMenu)

    def retranslateUi(self, OnitamaGameMenu):
        _translate = QtCore.QCoreApplication.translate
        OnitamaGameMenu.setWindowTitle(_translate("OnitamaGameMenu", "MainWindow"))
        self.quit.setText(_translate("OnitamaGameMenu", "quitter"))
        self.mode_selection.setTitle(_translate("OnitamaGameMenu", "Sélection du mode"))
        self.label.setText(_translate("OnitamaGameMenu", "Mode normal"))
        self.label_2.setText(_translate("OnitamaGameMenu", "L\'esprit du vent"))
        self.label_3.setText(_translate("OnitamaGameMenu", "La voie du Maître"))
        self.mode1.setText(_translate("OnitamaGameMenu", "Mode normal"))
        self.mode21.setText(_translate("OnitamaGameMenu", "Calme"))
        self.mode22.setText(_translate("OnitamaGameMenu", "Brise du matin"))
        self.mode23.setText(_translate("OnitamaGameMenu", "Vent léger"))
        self.mode25.setText(_translate("OnitamaGameMenu", "Ouragan"))
        self.mode24.setText(_translate("OnitamaGameMenu", "Tempête"))
        self.mode26.setText(_translate("OnitamaGameMenu", "ONITAMA DOIT MOURIR"))
        self.mode3.setText(_translate("OnitamaGameMenu", "La voie du Maître"))
        self.rules.setText(_translate("OnitamaGameMenu", "Règles"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    OnitamaGameMenu = QtWidgets.QMainWindow()
    ui = Ui_OnitamaGameMenu()
    ui.setupUi(OnitamaGameMenu)
    OnitamaGameMenu.show()
    sys.exit(app.exec_())
